{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "marimo-operator.fullname" . }}-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marimo-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      tlsConfig:
        {{- if .Values.metrics.serviceMonitor.tlsConfig }}
        {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 8 }}
        {{- else }}
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
        {{- end }}
  selector:
    matchLabels:
      {{- include "marimo-operator.selectorLabels" . | nindent 6 }}
{{- end }}
